[package]
name = "network_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8.4"
heapless = "0.9.2"
network_types = { path = "./network-types" }
postcard = {version = "1.1.3", features=["use-std"]}
serde = "1.0.228"
